Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/09/2022
Var
// Seção de Declarações das variáveis 
cont : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   para cont de 1 ate 10 passo 2 faca
        escreval (cont)
   fimpara

   para cont de 10 ate 1 passo -1 faca
        escreval(cont)
   fimpara

Fimalgoritmo