Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/09/2022
Var
// Seção de Declarações das variáveis 
nome : caracter
cont : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("Escreva seu nome")
leia (nome)


para cont de 1 ate 10 faca
escreval (nome)
fimpara


Fimalgoritmo