Algoritmo "REPETICAO_REPITAATE"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/10/2022
Var
// Seção de Declarações das variáveis 
cont : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   cont := 0
   repita
       escreval ("Contando" , cont)
       cont := cont + 1
   ate cont = 10


Fimalgoritmo